package com.example.dto;

import java.io.Serializable;
import java.util.Date;
/**
 * 답변 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Answer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qna_답변번호. */
	private Integer answerNo;

	/** qna_답변내용. */
	private String answerContent;

	private Date answerDate;
	/** qna게시판. */
	private Integer qnaNo;

	/** 사용자. */
	private String userId;

	private Users users;

	public Answer(Integer answerNo, String answerContent, Date answerDate, Integer qnaNo, String userId) {
		super();
		this.answerNo = answerNo;
		this.answerContent = answerContent;
		this.answerDate = answerDate;
		this.qnaNo = qnaNo;
		this.userId = userId;
	}
	public Answer() {
	}
	public Integer getAnswerNo() {
		return answerNo;
	}

	public void setAnswerNo(Integer answerNo) {
		this.answerNo = answerNo;
	}

	public String getAnswerContent() {
		return answerContent;
	}

	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent;
	}

	public Date getAnswerDate() {
		return answerDate;
	}

	public void setAnswerDate(Date answerDate) {
		this.answerDate = answerDate;
	}

	public Integer getQnaNo() {
		return qnaNo;
	}

	public void setQnaNo(Integer qnaNo) {
		this.qnaNo = qnaNo;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	
}
