package com.example.dto;

import java.io.Serializable;

/**
 * 답변 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Answer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qna_답변번호. */
	private Integer answerNo;

	/** qna_답변내용. */
	private String answerContent;

	/** qna게시판. */
	private Qna qna;

	/** 사용자. */
	private Users users;

	/**
	 * 생성자.
	 */
	public Answer() {
	}

	/**
	 * qna_답변번호을 설정합니다..
	 * 
	 * @param answerNo
	 *            qna_답변번호
	 */
	public void setAnswerNo(Integer answerNo) {
		this.answerNo = answerNo;
	}

	/**
	 * qna_답변번호을 가져옵니다..
	 * 
	 * @return qna_답변번호
	 */
	public Integer getAnswerNo() {
		return this.answerNo;
	}

	/**
	 * qna_답변내용을 설정합니다..
	 * 
	 * @param answerContent
	 *            qna_답변내용
	 */
	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent;
	}

	/**
	 * qna_답변내용을 가져옵니다..
	 * 
	 * @return qna_답변내용
	 */
	public String getAnswerContent() {
		return this.answerContent;
	}

	/**
	 * qna게시판을 설정합니다..
	 * 
	 * @param qna
	 *            qna게시판
	 */
	public void setQna(Qna qna) {
		this.qna = qna;
	}

	/**
	 * qna게시판을 가져옵니다..
	 * 
	 * @return qna게시판
	 */
	public Qna getQna() {
		return this.qna;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((answerNo == null) ? 0 : answerNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Answer other = (Answer) obj;
		if (answerNo == null) {
			if (other.answerNo != null) {
				return false;
			}
		} else if (!answerNo.equals(other.answerNo)) {
			return false;
		}
		return true;
	}

}
