package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 게시글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Comments implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글_번호. */
	private Integer commentNo;

	/** 게시글_분류. */
	private String commentCategory;

	/** 게시글_이름. */
	private String commentName;

	/** 게시글_내용. */
	private String commentContent;

	/** 게시글_날짜. */
	private Date commentDate;

	private Integer commentCount;
	/** 사용자. */
	private String userId;
	
	private Users users;
	
	private Integer RNUM;
	
	public Comments(Integer commentNo, String commentCategory, String commentName, String commentContent,
			Date commentDate, Integer commentCount, String userId) {
		super();
		this.commentNo = commentNo;
		this.commentCategory = commentCategory;
		this.commentName = commentName;
		this.commentContent = commentContent;
		this.commentDate = commentDate;
		this.commentCount = commentCount;
		this.userId = userId;
	}

	
	
}
