package com.example.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 게시글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Comments implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글_번호. */
	private Integer commentNo;

	/** 게시글_분류. */
	private String commentCategory;

	/** 게시글_이름. */
	private String commentName;

	/** 게시글_내용. */
	private String commentContent;

	/** 게시글_날짜. */
	private Date commentDate;

	private Integer commentCount;
	/** 사용자. */
	private String userId;
	
	private Users users;
	
	private Integer RNUM;
	
	public Comments() {
	}
	
	public Comments(Integer commentNo, String commentCategory, String commentName, String commentContent,
			Date commentDate, Integer commentCount, String userId) {
		super();
		this.commentNo = commentNo;
		this.commentCategory = commentCategory;
		this.commentName = commentName;
		this.commentContent = commentContent;
		this.commentDate = commentDate;
		this.commentCount = commentCount;
		this.userId = userId;
	}

	public Integer getCommentNo() {
		return commentNo;
	}

	public void setCommentNo(Integer commentNo) {
		this.commentNo = commentNo;
	}

	public String getCommentCategory() {
		return commentCategory;
	}

	public void setCommentCategory(String commentCategory) {
		this.commentCategory = commentCategory;
	}

	public String getCommentName() {
		return commentName;
	}

	public void setCommentName(String commentName) {
		this.commentName = commentName;
	}

	public String getCommentContent() {
		return commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	public Date getCommentDate() {
		return commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	public Integer getCommentCount() {
		return commentCount;
	}

	public void setCommentCount(Integer commentCount) {
		this.commentCount = commentCount;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Integer getRNUM() {
		return RNUM;
	}

	public void setRNUM(Integer rNUM) {
		RNUM = rNUM;
	}

	
	
}
