package com.example.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 게시글_댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommentReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글_번호. */
	private Integer replyNo;

	/** 댓글_내용. */
	private String replyContent;

	/** 댓글_날짜. */
	private Date replyDate;

	/** 게시글. */
	private Integer replyCommentNo;

	/** 사용자. */
	private String userId;

	private Users users;

	public CommentReply(Integer replyNo, String replyContent, Date replyDate, Integer replyCommentNo, String userId) {
		super();
		this.replyNo = replyNo;
		this.replyContent = replyContent;
		this.replyDate = replyDate;
		this.replyCommentNo = replyCommentNo;
		this.userId = userId;
	}
	public CommentReply() {
	}
	
	public Integer getReplyNo() {
		return replyNo;
	}

	public void setReplyNo(Integer replyNo) {
		this.replyNo = replyNo;
	}

	public String getReplyContent() {
		return replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public Date getReplyDate() {
		return replyDate;
	}

	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	public Integer getReplyCommentNo() {
		return replyCommentNo;
	}

	public void setReplyCommentNo(Integer replyCommentNo) {
		this.replyCommentNo = replyCommentNo;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	
}
