package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 포토북 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class PhotoBook implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 포토북_공유한폴더. */
	private String photoFolderName;

	/** 사용자. */
	private String userId;

	/** 포토북_공유자1. */
	private String photoShareId1;

	/** 포토북_공유자2. */
	private String photoShareId2;

	/** 포토북_공유자3. */
	private String photoShareId3;

	/** 포토북_공유자4. */
	private String photoShareId4;

	private Users users;
	public PhotoBook(String photoFolderName, String userId, String photoShareId1, String photoShareId2,
			String photoShareId3, String photoShareId4) {
		super();
		this.photoFolderName = photoFolderName;
		this.userId = userId;
		this.photoShareId1 = photoShareId1;
		this.photoShareId2 = photoShareId2;
		this.photoShareId3 = photoShareId3;
		this.photoShareId4 = photoShareId4;
	}
	
	

}
