package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 포토북 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Photobook implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 포토북_공유한폴더. */
	private String photoShare;

	/** 포토북_공유받은폴더. */
	private String photoShared;

	/** 사용자. */
	private Users users;

	/** 포토북_공유자1. */
	private String photoShareId1;

	/** 포토북_공유자2. */
	private String photoShareId2;

	/** 포토북_공유자3. */
	private String photoShareId3;

	/** 포토북_공유자4. */
	private String photoShareId4;

}
