package com.example.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * qna게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Qna implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qna_번호. */
	private Integer qnaNo;

	/** qna_제목. */
	private String qnaTitle;

	/** qna_내용. */
	private String qnaQuestion;

	/** 사용자. */
	private Users users;

	/** 답변 목록. */
	private Set<Answer> answerSet;

	/**
	 * 생성자.
	 */
	public Qna() {
		this.answerSet = new HashSet<Answer>();
	}

	/**
	 * qna_번호을 설정합니다..
	 * 
	 * @param qnaNo
	 *            qna_번호
	 */
	public void setQnaNo(Integer qnaNo) {
		this.qnaNo = qnaNo;
	}

	/**
	 * qna_번호을 가져옵니다..
	 * 
	 * @return qna_번호
	 */
	public Integer getQnaNo() {
		return this.qnaNo;
	}

	/**
	 * qna_제목을 설정합니다..
	 * 
	 * @param qnaTitle
	 *            qna_제목
	 */
	public void setQnaTitle(String qnaTitle) {
		this.qnaTitle = qnaTitle;
	}

	/**
	 * qna_제목을 가져옵니다..
	 * 
	 * @return qna_제목
	 */
	public String getQnaTitle() {
		return this.qnaTitle;
	}

	/**
	 * qna_내용을 설정합니다..
	 * 
	 * @param qnaQuestion
	 *            qna_내용
	 */
	public void setQnaQuestion(String qnaQuestion) {
		this.qnaQuestion = qnaQuestion;
	}

	/**
	 * qna_내용을 가져옵니다..
	 * 
	 * @return qna_내용
	 */
	public String getQnaQuestion() {
		return this.qnaQuestion;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 답변 목록을 설정합니다..
	 * 
	 * @param answerSet
	 *            답변 목록
	 */
	public void setAnswerSet(Set<Answer> answerSet) {
		this.answerSet = answerSet;
	}

	/**
	 * 답변를 추가합니다..
	 * 
	 * @param answer
	 *            답변
	 */
	public void addAnswer(Answer answer) {
		this.answerSet.add(answer);
	}

	/**
	 * 답변 목록을 가져옵니다..
	 * 
	 * @return 답변 목록
	 */
	public Set<Answer> getAnswerSet() {
		return this.answerSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qnaNo == null) ? 0 : qnaNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Qna other = (Qna) obj;
		if (qnaNo == null) {
			if (other.qnaNo != null) {
				return false;
			}
		} else if (!qnaNo.equals(other.qnaNo)) {
			return false;
		}
		return true;
	}

}
