package com.example.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * qna게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Qna implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** qna_번호. */
	private Integer qnaNo;

	/** qna_제목. */
	private String qnaTitle;

	/** qna_내용. */
	private String qnaQuestion;

	private Date qnaDate;
	private Integer qnaCount;
	/** 사용자. */
	private String userId;

	private Users users;

	public Qna(){
		
	}
	
	public Qna(Integer qnaNo, String qnaTitle, String qnaQuestion, Date qnaDate, Integer qnaCount, String userId) {
		super();
		this.qnaNo = qnaNo;
		this.qnaTitle = qnaTitle;
		this.qnaQuestion = qnaQuestion;
		this.qnaDate = qnaDate;
		this.qnaCount = qnaCount;
		this.userId = userId;
	}

	public Integer getQnaNo() {
		return qnaNo;
	}

	public void setQnaNo(Integer qnaNo) {
		this.qnaNo = qnaNo;
	}

	public String getQnaTitle() {
		return qnaTitle;
	}

	public void setQnaTitle(String qnaTitle) {
		this.qnaTitle = qnaTitle;
	}

	public String getQnaQuestion() {
		return qnaQuestion;
	}

	public void setQnaQuestion(String qnaQuestion) {
		this.qnaQuestion = qnaQuestion;
	}

	public Date getQnaDate() {
		return qnaDate;
	}

	public void setQnaDate(Date qnaDate) {
		this.qnaDate = qnaDate;
	}

	public Integer getQnaCount() {
		return qnaCount;
	}

	public void setQnaCount(Integer qnaCount) {
		this.qnaCount = qnaCount;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	
}
