package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 지역분류 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Region implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 시-도. */
	private String seedo;

	/** 군-구. */
	private String goongu;

	/** 동면읍리. */
	private String dong;

}
