package com.example.dto;

import java.io.Serializable;

/**
 * 지역분류 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Region implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private String si;

	private String xy;

	public Region(){
		
	}
	
	public Region(String si, String xy) {
		this.si = si;
		this.xy = xy;
	}

	public String getSi() {
		return si;
	}

	public void setSi(String si) {
		this.si = si;
	}

	public String getXy() {
		return xy;
	}

	public void setXy(String xy) {
		this.xy = xy;
	}


}
