package com.example.dto;

import java.io.Serializable;
import java.util.Date;

/**
 * 후기_댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReviewReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글_번호. */
	private Integer replyNo;

	/** 댓글_내용. */
	private String replyContent;

	/** 댓글_날짜. */
	private Date replyDate;

	/** 후기. */
	private Review replyReview;

	/** 사용자. */
	private Users users;

	/**
	 * 생성자.
	 */
	public ReviewReply() {
	}

	/**
	 * 댓글_번호을 설정합니다..
	 * 
	 * @param replyNo
	 *            댓글_번호
	 */
	public void setReplyNo(Integer replyNo) {
		this.replyNo = replyNo;
	}

	/**
	 * 댓글_번호을 가져옵니다..
	 * 
	 * @return 댓글_번호
	 */
	public Integer getReplyNo() {
		return this.replyNo;
	}

	/**
	 * 댓글_내용을 설정합니다..
	 * 
	 * @param replyContent
	 *            댓글_내용
	 */
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	/**
	 * 댓글_내용을 가져옵니다..
	 * 
	 * @return 댓글_내용
	 */
	public String getReplyContent() {
		return this.replyContent;
	}

	/**
	 * 댓글_날짜을 설정합니다..
	 * 
	 * @param replyDate
	 *            댓글_날짜
	 */
	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	/**
	 * 댓글_날짜을 가져옵니다..
	 * 
	 * @return 댓글_날짜
	 */
	public Date getReplyDate() {
		return this.replyDate;
	}

	/**
	 * 후기을 설정합니다..
	 * 
	 * @param replyReview
	 *            후기
	 */
	public void setReplyReview(Review replyReview) {
		this.replyReview = replyReview;
	}

	/**
	 * 후기을 가져옵니다..
	 * 
	 * @return 후기
	 */
	public Review getReplyReview() {
		return this.replyReview;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((replyNo == null) ? 0 : replyNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ReviewReply other = (ReviewReply) obj;
		if (replyNo == null) {
			if (other.replyNo != null) {
				return false;
			}
		} else if (!replyNo.equals(other.replyNo)) {
			return false;
		}
		return true;
	}

}
