package com.example.dto;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 후기 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Review implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 후기_번호. */
	private Integer reviewNo;

	/** 후기_이름. */
	private String reviewTitle;

	/** 후기_내용. */
	private String reviewContent;

	/** 후기_날짜. */
	private Date reviewDate;

	/** 후기_추천수. */
	private Integer reviewStar;

	private Integer reviewCount;
	/** 경로. */
	private Integer routeNo;

	/** 사용자. */
	private String userId;

	private Users users;

	public Review(Integer reviewNo, String reviewTitle, String reviewContent, Date reviewDate, Integer reviewStar,
			Integer reviewCount, Integer routeNo, String userId) {
		super();
		this.reviewNo = reviewNo;
		this.reviewTitle = reviewTitle;
		this.reviewContent = reviewContent;
		this.reviewDate = reviewDate;
		this.reviewStar = reviewStar;
		this.reviewCount = reviewCount;
		this.routeNo = routeNo;
		this.userId = userId;
	}
	
	
}
