package com.example.dto;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 후기 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Review implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 후기_번호. */
	private Integer reviewNo;

	/** 후기_이름. */
	private String reviewTitle;

	/** 후기_내용. */
	private String reviewContent0;
	private String reviewContent1;
	private String reviewContent2;
	private String reviewContent3;
	private String reviewContent4;
	private String reviewContent5;
	private String reviewContent6;
	private String reviewContent7;
	private String reviewContent8;
	private String reviewContent9;
	/** 후기_날짜. */
	private Date reviewDate;

	/** 후기_추천수. */
	private Integer reviewStar;

	/** 후기 메인사진 */
	private String reviewImage;
	private Integer reviewCount;
	/** 경로. */
	private Integer routeNo;

	/** 사용자. */
	private String userId;

	private Users users;

	private Route route;

	public Review(Integer reviewNo, String reviewTitle, String reviewContent0, String reviewContent1,
			String reviewContent2, String reviewContent3, String reviewContent4, String reviewContent5,
			String reviewContent6, String reviewContent7, String reviewContent8, String reviewContent9,
			Date reviewDate,Integer reviewStar, Integer reviewCount, Integer routeNo, String userId,Route route) {
		super();
		this.reviewNo = reviewNo;
		this.reviewTitle = reviewTitle;
		this.reviewContent0 = reviewContent0;
		this.reviewContent1 = reviewContent1;
		this.reviewContent2 = reviewContent2;
		this.reviewContent3 = reviewContent3;
		this.reviewContent4 = reviewContent4;
		this.reviewContent5 = reviewContent5;
		this.reviewContent6 = reviewContent6;
		this.reviewContent7 = reviewContent7;
		this.reviewContent8 = reviewContent8;
		this.reviewContent9 = reviewContent9;
		this.reviewDate = reviewDate;
		this.reviewStar = reviewStar;
		this.reviewCount = reviewCount;
		this.routeNo = routeNo;
		this.userId = userId;
		this.route = route;
	}
	
	
	
}
