package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 경로 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Route implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 경로_번호. */
	private Integer routeNo;

	private String routeName;
	/** 경로_내용. */
	private String routeContent;

	/** 경로_세부지도. */
	private String routeFull;

	/** 경로_시지도. */
	private String routeCity;

	/** 경로_도지도. */
	private String routeDo;

	/** 경로_날짜. */
	private Date routeDate;

	/** 사용자. */
	private String userId;


}
