package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 경로 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Route implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 경로_번호. */
	private Integer routeNo;

	/** 경로_내용. */
	private String routeContent;

	/** 경로_세부지도. */
	private String routeFull;

	/** 경로_시지도. */
	private String routeCity;

	/** 경로_도지도. */
	private String routeDo;

	/** 경로_날짜. */
	private Date routeDate;

	/** 사용자. */
	private Users users;

	/** 지역분류. */
	private Region region;

	/** 후기 목록. */
	private Set<Review> reviewSet;

	/**
	 * 생성자.
	 */
	public Route() {
		this.reviewSet = new HashSet<Review>();
	}

	/**
	 * 경로_번호을 설정합니다..
	 * 
	 * @param routeNo
	 *            경로_번호
	 */
	public void setRouteNo(Integer routeNo) {
		this.routeNo = routeNo;
	}

	/**
	 * 경로_번호을 가져옵니다..
	 * 
	 * @return 경로_번호
	 */
	public Integer getRouteNo() {
		return this.routeNo;
	}

	/**
	 * 경로_내용을 설정합니다..
	 * 
	 * @param routeContent
	 *            경로_내용
	 */
	public void setRouteContent(String routeContent) {
		this.routeContent = routeContent;
	}

	/**
	 * 경로_내용을 가져옵니다..
	 * 
	 * @return 경로_내용
	 */
	public String getRouteContent() {
		return this.routeContent;
	}

	/**
	 * 경로_세부지도을 설정합니다..
	 * 
	 * @param routeFull
	 *            경로_세부지도
	 */
	public void setRouteFull(String routeFull) {
		this.routeFull = routeFull;
	}

	/**
	 * 경로_세부지도을 가져옵니다..
	 * 
	 * @return 경로_세부지도
	 */
	public String getRouteFull() {
		return this.routeFull;
	}

	/**
	 * 경로_시지도을 설정합니다..
	 * 
	 * @param routeCity
	 *            경로_시지도
	 */
	public void setRouteCity(String routeCity) {
		this.routeCity = routeCity;
	}

	/**
	 * 경로_시지도을 가져옵니다..
	 * 
	 * @return 경로_시지도
	 */
	public String getRouteCity() {
		return this.routeCity;
	}

	/**
	 * 경로_도지도을 설정합니다..
	 * 
	 * @param routeDo
	 *            경로_도지도
	 */
	public void setRouteDo(String routeDo) {
		this.routeDo = routeDo;
	}

	/**
	 * 경로_도지도을 가져옵니다..
	 * 
	 * @return 경로_도지도
	 */
	public String getRouteDo() {
		return this.routeDo;
	}

	/**
	 * 경로_날짜을 설정합니다..
	 * 
	 * @param routeDate
	 *            경로_날짜
	 */
	public void setRouteDate(Date routeDate) {
		this.routeDate = routeDate;
	}

	/**
	 * 경로_날짜을 가져옵니다..
	 * 
	 * @return 경로_날짜
	 */
	public Date getRouteDate() {
		return this.routeDate;
	}

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param users
	 *            사용자
	 */
	public void setUsers(Users users) {
		this.users = users;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Users getUsers() {
		return this.users;
	}

	/**
	 * 지역분류을 설정합니다..
	 * 
	 * @param region
	 *            지역분류
	 */
	public void setRegion(Region region) {
		this.region = region;
	}

	/**
	 * 지역분류을 가져옵니다..
	 * 
	 * @return 지역분류
	 */
	public Region getRegion() {
		return this.region;
	}

	/**
	 * 후기 목록을 설정합니다..
	 * 
	 * @param reviewSet
	 *            후기 목록
	 */
	public void setReviewSet(Set<Review> reviewSet) {
		this.reviewSet = reviewSet;
	}

	/**
	 * 후기를 추가합니다..
	 * 
	 * @param review
	 *            후기
	 */
	public void addReview(Review review) {
		this.reviewSet.add(review);
	}

	/**
	 * 후기 목록을 가져옵니다..
	 * 
	 * @return 후기 목록
	 */
	public Set<Review> getReviewSet() {
		return this.reviewSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((routeNo == null) ? 0 : routeNo.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Route other = (Route) obj;
		if (routeNo == null) {
			if (other.routeNo != null) {
				return false;
			}
		} else if (!routeNo.equals(other.routeNo)) {
			return false;
		}
		return true;
	}

}
