package com.example.dto;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * 경로 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Route implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 경로_번호. */
	private Integer routeNo;

	/** 경로_이름. */
	private String routeName;
	
	/** 경로_내용. */
	private String routeContent;

	/** 경로_세부지도. */
	private String routeFull;

	/** 경로_날짜. */
	private Date routeDate;

	/** 사용자. */
	private String userId;

	private Users users;
	
	public Route(Integer routeNo, String routeName, String routeContent, String routeFull, Date routeDate,
			String userId) {
		super();
		this.routeNo = routeNo;
		this.routeName = routeName;
		this.routeContent = routeContent;
		this.routeFull = routeFull;
		this.routeDate = routeDate;
		this.userId = userId;
	}


}
