package com.example.dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@AllArgsConstructor
@Data
@NoArgsConstructor
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자_id. */
	private String userId;

	/** 사용자_이름. */
	private String userName;
	
	/** 사용자_비밀번호. */
	private String userPass;

	/** 사용자_이메일. */
	private String userEmail;

	/** 사용자_전화번호. */
	private String userPhone;

	/** 사용자_별명. */
	private String userNick;

	private Review review;

	private Qna qna;
	
	private Answer answer;
	
	public Users(String userId, String userPass, String userName, String userEmail, String userPhone, String userNick) {
		super();
		this.userId = userId;
		this.userPass = userPass;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPhone = userPhone;
		this.userNick = userNick;
	}

	
}
